### ISSUE TITLE
Issue while running demo_clock.py

### ISSUE THREAD

**Issue by rinkucool007** [the-raspberry-pi-guy/lcd#28]
pi@raspberrypi:~/lcd $ python demo_clock.py
Traceback (most recent call last):
  File "demo_clock.py", line 14, in <module>
    display = drivers.Lcd()
  File "/home/pi/lcd/drivers/i2c_dev.py", line 103, in __init__
    self.lcd_write(0x03)
  File "/home/pi/lcd/drivers/i2c_dev.py", line 126, in lcd_write
    self.lcd_write_four_bits(mode | (cmd & 0xF0))
  File "/home/pi/lcd/drivers/i2c_dev.py", line 121, in lcd_write_four_bits
    self.lcd.write_cmd(data | LCD_BACKLIGHT)
  File "/home/pi/lcd/drivers/i2c_dev.py", line 74, in write_cmd
    self.bus.write_byte(self.addr, cmd)
IOError: [Errno 121] Remote I/O error

**Comment by cgomesu** [comment]
@rinkucool007 , try patching the changes in #27 and run the `demo_clock.py` script again.  If the error continues, double check your connections.

When replying to this message, paste the output of the following commands:
```
python --version
```
```
i2cdetect -y 1
```
```
hostnamectl
```
and if possible, let us know about the specifics of your LCD module.
